default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gadoLeague_development

test:
  <<: *default
  database: gadoLeague_test

production:
  <<: *default
  database: gadoLeague_production
  username: gadoLeague
  password: <%= ENV['GADOLEAGUE_DATABASE_PASSWORD'] %>
